# Generated by Django 4.0.2 on 2022-11-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'flight', 'verbose_name_plural': 'flights'},
        ),
        migrations.AlterModelOptions(
            name='rocket',
            options={'verbose_name': 'rocket', 'verbose_name_plural': 'rockets'},
        ),
        migrations.AddField(
            model_name='rocket',
            name='image',
            field=models.ImageField(blank=True, upload_to='router_image'),
        ),
    ]
